#:kivy 1.0

<RubberDucky>:
    BoxLayout:
        padding: 20
        spacing: 10

        Button:
            font_size: '13sp'
            text: "RubberDucky is an interpreted languange"
            text_size: self.size
            halign: 'center'
            valign: 'middle'

        Button:
            text: "Sometimes all it takes is to talk it out to a Rubber Ducky"
            text_size: self.size
            halign: 'center'
            valign: 'middle'
